Schemes
izhatomic/mattermost-api pull request #40
Opened 2023-11-06 18:50 UTC by Tigonite

Создал mm_schemes_api.py

2023-11-17 18:10 UTC, izhatomic commented on Mattermost-API/mm_schemes_api.py
> +        url = f"{self.api_url}/"
палка направо лишняя

2023-11-17 18:18 UTC, izhatomic requested changes
В одном месте поправь :)

2023-11-18 11:00 UTC, Tigonite commented
Поправил

2023-11-19 16:54 UTC, izhatomic commented
Закрываю как лишний. Работаем с веткой **prferences** и делаем все исправления там.

2023-11-19 16:54 UTC, closed without merging