Roles
izhatomic/mattermost-api pull request #41
Opened 2023-11-06 20:36 UTC by Tigonite

Создал mm_roles_api.py

2023-11-17 18:19 UTC, izhatomic commented on Mattermost-API/mm_roles_api.py
> +        url = f"{self.api_url}/"
Опять палка направо лишняя :)

2023-11-17 18:21 UTC, izhatomic requested changes
Ты ветки от мэйн отводишь или от последней ветки? Судя по тому, что каждый пул реквест содержит предыдущие изменения, то ты не от мэйна отводишься.

2023-11-18 11:02 UTC, Tigonite commented
Поправил

2023-11-19 16:54 UTC, izhatomic commented
Закрываю как лишний. Работаем с веткой **prferences** и делаем все исправления там.

2023-11-19 16:54 UTC, closed without merging