Integration actions
izhatomic/mattermost-api pull request #6
Opened 2023-04-17 20:52 UTC by Tigonite

Создал файл mm_int_actions_api.py

2023-04-21 15:39 UTC, izhatomic requested changes

2023-04-21 15:39 UTC, izhatomic commented on Mattermost-API/mm_int_actions_api.py
> +    def open_dialog(self, trigger_id: str
Про запятые то забыл :) У тебя же PyCharm ругаться на это должен.

2023-04-21 15:39 UTC, izhatomic commented on Mattermost-API/mm_int_actions_api.py
> +    url = f"{self.api_url}/open"
Кажется у тебя отступы во всем файле съехали.

2023-04-21 15:39 UTC, izhatomic commented on Mattermost-API/mm_int_actions_api.py
> +                      team_id: str
Про запятые не забываем...

2023-04-21 15:39 UTC, izhatomic commented on Mattermost-API/mm_int_actions_api.py
> +    self.add_to_json('cancelled', cancelled)
Отступы

2023-04-25 20:43 UTC, Tigonite commented
Откоректировал файл mm_int_actions_api.py

2023-05-11 19:25 UTC, Tigonite commented
Попробовал сделать как ты сказал. Удалил .idea через терминал

2023-05-11 19:58 UTC, izhatomic commented
А коммит потом сделал? Пул реквест обновил? Потому что сейчас в пул реквесте ничего не изменилось - все лишние файлы все там же.

2023-05-16 16:18 UTC, izhatomic approved these changes

2023-05-16 16:18 UTC, merged